"""empty message

Revision ID: 208cac1a807d
Revises: d91a3da4f312
Create Date: 2016-06-16 17:40:58.820918

"""

# revision identifiers, used by Alembic.
revision = '208cac1a807d'
down_revision = 'd91a3da4f312'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_info', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_info', 'timestamp')
    ### end Alembic commands ###
