"""empty message

Revision ID: 353ade6c2c18
Revises: None
Create Date: 2016-06-07 14:45:58.262175

"""

# revision identifiers, used by Alembic.
revision = '353ade6c2c18'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ad_info')
    ### end Alembic commands ###
