"""empty message

Revision ID: 55a696eebb60
Revises: 353ade6c2c18
Create Date: 2016-06-08 07:05:19.105842

"""

# revision identifiers, used by Alembic.
revision = '55a696eebb60'
down_revision = '353ade6c2c18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_info', sa.Column('ad_body', sa.String(), nullable=True))
    op.add_column('ad_info', sa.Column('location', sa.String(), nullable=True))
    op.add_column('ad_info', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('ad_info', sa.Column('photos', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_info', 'photos')
    op.drop_column('ad_info', 'phone_number')
    op.drop_column('ad_info', 'location')
    op.drop_column('ad_info', 'ad_body')
    ### end Alembic commands ###
