"""empty message

Revision ID: 19b40328c6cb
Revises: eca092c127d8
Create Date: 2017-05-29 15:04:29.571670

"""

# revision identifiers, used by Alembic.
revision = '19b40328c6cb'
down_revision = 'eca092c127d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areacode_lookup', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('areacode_lookup', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areacode_lookup', 'longitude')
    op.drop_column('areacode_lookup', 'latitude')
    # ### end Alembic commands ###
