"""empty message

Revision ID: 3fe295f88b49
Revises: 907bade2acf1
Create Date: 2017-05-23 15:06:40.128657

"""

# revision identifiers, used by Alembic.
revision = '3fe295f88b49'
down_revision = '907bade2acf1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_to_text', sa.Column('throw_away', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_to_text', 'throw_away')
    # ### end Alembic commands ###
