"""empty message

Revision ID: 907bade2acf1
Revises: b319bba5d9a8
Create Date: 2017-05-20 15:19:47.379513

"""

# revision identifiers, used by Alembic.
revision = '907bade2acf1'
down_revision = 'b319bba5d9a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_to_text', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_to_text', 'image_url')
    # ### end Alembic commands ###
