"""empty message

Revision ID: b319bba5d9a8
Revises: bcc82a7dcc31
Create Date: 2017-05-20 15:07:44.515667

"""

# revision identifiers, used by Alembic.
revision = 'b319bba5d9a8'
down_revision = 'bcc82a7dcc31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_to_text', sa.Column('city', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('filename', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('location', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('state', sa.String(), nullable=True))
    op.add_column('image_to_text', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('image_to_text', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('image_to_text', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_to_text', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('image_to_text', 'url')
    op.drop_column('image_to_text', 'timestamp')
    op.drop_column('image_to_text', 'state')
    op.drop_column('image_to_text', 'phone_number')
    op.drop_column('image_to_text', 'longitude')
    op.drop_column('image_to_text', 'location')
    op.drop_column('image_to_text', 'latitude')
    op.drop_column('image_to_text', 'filename')
    op.drop_column('image_to_text', 'city')
    # ### end Alembic commands ###
