"""empty message

Revision ID: b9fabcf684b6
Revises: None
Create Date: 2017-04-30 07:16:29.016633

"""

# revision identifiers, used by Alembic.
revision = 'b9fabcf684b6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areacode_lookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_code', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areacode_lookup')
    ### end Alembic commands ###
