"""empty message

Revision ID: c4f058e59bf1
Revises: 75a9a634acd6
Create Date: 2017-05-13 15:10:44.499740

"""

# revision identifiers, used by Alembic.
revision = 'c4f058e59bf1'
down_revision = '75a9a634acd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_info', sa.Column('url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_info', 'url')
    ### end Alembic commands ###
