"""empty message

Revision ID: eca092c127d8
Revises: 3fe295f88b49
Create Date: 2017-05-29 14:43:23.128504

"""

# revision identifiers, used by Alembic.
revision = 'eca092c127d8'
down_revision = '3fe295f88b49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areacode_lookup', sa.Column('city', sa.String(), nullable=True))
    op.add_column('areacode_lookup', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('areacode_lookup', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areacode_lookup', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('areacode_lookup', 'state')
    op.drop_column('areacode_lookup', 'city')
    # ### end Alembic commands ###
