from app import visualize_metrics


visualize_metrics.visualize_month_over_month()
visualize_metrics.visualize_day_hour()
visualize_metrics.visualize_unique_day_hour()
visualize_metrics.visualize_unique_month_over_month()
